### ISSUE TITLE
Predefinisani projekat za 60 bodova(ocene 9 i 10)

### ISSUE THREAD

**Issue by lazic1701** [ftn-ai-lab/sc-2018-e2#120]
**Član:** Milan Lazić RA78-2018, grupa 5

**Asistent:** @ivan7792

**Problem:** Na osnovu fotografije neba sa zemlje prepoznaju se oblaci i klasifikuju se u 4 kategorije: ciro-forma, strato-forma, cumulo-forma i nimbo-forma. Svaka od ove 4 kategorije nosi određenu informaciju o vremenskim uslovima na zemlji koji će u bližem vremeskom periodu uslediti. Zaključak klasifikacije bi bio generisanje opisne kratkoročne vremenske prognoze padavina u zavisnosti od procenata prepoznavanja tipa oblaka na izlazu CNN. Tačnu formulu ću napraviti na osnovu istraživanja iz polja meteorologije i kasnije je navesti.

**Metodologija:** Skaliranje fotografija na male dimenzije zbog ograničenosti resursima. Korištenje konvulucione neuronske mreže Keras(Tensorflow) implementacije za Python 2.7 u okviru Google Colab platofme (zbog ograničenosti fizičkim resursima). Izlaz u obliku ispisa u konzoli opisne kratkoročne vremenske prognoze.

**Podaci:** Planiram da prikupim oko 600 fotografija sve 4 kategorije (po 150 za svaku) što online slika, što sopstvenih fotografija, što fotografija izvučenih iz timelapse videa. Sve fotografije ću posebno labelirati na osnovu kategorije kojoj oblak pripada koristeći nezavidno ali ipak, za ovaj zadatak, dovoljno znanje iz polja meteorologije. 

**Metrika:** Podaci će biti podeljeni na trening i test dataset u odnosu 9:1. Metrika će podrazumevati procenat tačnosti prepoznavanja sve 4 kategorije. Validacija se vrši na osnovu poređenja informacije koju nosi labela koju slika u test setu poseduje i izlaza CNN.

**Github Repo:** https://github.com/lazicy/cloud-forecast

**Comment by ivan7792** [comment]
- Što se tiče CNN pristupa za klasifikaciju slika, to se može uraditi pomoću gotovih Keras implementacija uz zamenu skupa podataka. U tom slučaju se projekat može uraditi za par minuta. Na usmenom ispitu bi onda fokus bio na konvolutivnim neuronskim mrežama i njihovim teorijskim osnovama. Ovakva implementacija je uz odličan usmeni ispit, za maksimalnu ocenu 8.

- Za više ocene morate probati neke druge pristupe. Da li ćete probati segmentaciju oblaka tehnikama koje smo radili na vežbama, ili nešto treće, to je na Vama. Kada imate dva pristupa, imaćete materijala da ih uporedite i napravite lep poster.

- Generisanje kratkorične progonze niste dovoljno opisali, a ovaj deo ima potencijala za nešto interesantno. Ukoliko u ovom delu napravite nešto dobro, zaista bazirano na tehnikama računarske inteligencije, taj deo može biti umesto alternativnog pristupa konvolutivnim mrežama.

Takođe, 600 slika će teško biti dovoljno za CNN pristup kod ovakvog problema (oblaci su jako slični). Možete probati takvo obučavanje, ali je teško očekivati dobre rezultate. Ovo takođe imajte u vidu. Labeliranje podataka će vam oduzeti veliku količinu vremena, pa se nadam da računate na to. U slučaju da zbog toga odustanete od ove teme, možete uzeti predefinisani projekat.

**Comment by lazic1701** [comment]
Ipak ću se odlučiti za predefinisani projekat zbog malo vremena preostalog da bih formirao skup podataka. Da li je potrebno da otvaram novi issue?

**Comment by ivan7792** [comment]
Nije potrebno kolega. Samo preimenujte ovaj Issue.

Ukoliko na masteru budete slušali predmete iz oblasti računarske inteligencije, ovu ideju za projekat možete iskoristiti. Tada ćete imati više vremena za prikupljanje podataka.
