### ISSUE TITLE
Pronalaženje najsličnijeg NBA košarkaša datom licu

### ISSUE THREAD

**Issue by stefan096** [ftn-ai-lab/sc-2018-e2#13]
1.  Članovi Tima :
 - Stefan Bokić RA87-2015
 - Katarina-Glorija Grujić RA3-2015
Asistent: Ivan Perić, @ivan7792
Grupa: 5

2. Problem koji rešava:
- Na osnovu zadatog lica od strane korisnika pronalaženje najsličnijeg NBA košarkaša datom licu. 

3. Algoritam/algoritmi koji će se koristiti:
- HOG
- Sliding window
- dlib - biblioteka za izvlačenje 68 tačaka lica
- openCV - rad sa slikama
- KNN - pronalazenje najbliže slike zadatoj
- Neuronska mreža - feed forward - pronalazenje najbliže slike zadatoj

4. Metrika za poređenje performansi algoritama i/ili parametara algoritma:
- Rastojanje 68 izvučenih tačaka jednog lica od drugog.

5. Podaci koji se koriste:
- Podaci su prikupljeni sa sajta https://www.nba.com . Skidane su slike pomocu seleniuma i labele koje predstavljaju imena košarkaša. Formiran je skup od 500 slika.

6. Na koji način planirate validaciju rešenja
 - Skinućemo slike željenog košarkaša koji se pojavljuje u trening skupu ali slikanog na drugoj pozadini iz druge perspektive (slika je uvećana/umanjena ili zarotirana)

7.  Link ka repozitorijumu:
https://github.com/stefan096/Projekat-Soft-Izgled

**Comment by ivan7792** [comment]
Kod KNN probajte zazličite tipove rastojanja i uporedite ih, a kod neuronske mreže možete obratiti pažnju na "Siamese Networks" i njihovu implementaciju u kerasu.

Tema odobrena, srećan rad.
