### ISSUE TITLE
Klasifikacija mladeža

### ISSUE THREAD

**Issue by SimicSvetislav** [ftn-ai-lab/sc-2018-e2#142]
- **Članovi tima:**
Svetislav Simić RA116/2015, grupa 6
Asistent: Stefan Anđelić, @StefanAndjelic

- **Motivacija:**
Mogućnost da svako samostalno može da potvrdi bezazlenost mladeža bi smanjila nepotrebne odlaske kod lekara i samim tim lekari bi mogli više vremena da posvete kritičnijim pacijentima. Težnja aplikacije ne bi bila da nužno precizno razvrsta svaki mladež već da ne postoji maligni mladež koji nije prijavljen kao opasan.

- **Opis problema:**
Potrebno je izvršiti binarnu klasifikaciju dobijene slike na osnovu toga da li je mladež potencijalno opasan ili nije.
Model je potrebno istrenirati na označenim podacima i ekstrahovanim obeležjima.
Potom se vrši klasifikacija slika koje se dovode na ulaz. 
Postupak obrade pojedinačne slike bi išao na sledeći način:
 1. pretprocesiranje radi uklanjanja šuma i nerelevantnih segmenata slike
 2. ekstrakcija željenih obeležja u koje spadaju simetričnost, oblik ivica, varijacija boje i dimenzije mladeža
 3. klasifikacija mladeža sa slike kao benignog ili potencijalno malignog 

- **Algoritmi:**
1. za pretprocesiranje: Gausovo zamućenje, dilacija, erozija
2. za ekstrakciju obeležja: Hough transformacija, HOG deskriptor, Canny, Fast Radial Symmetry Transform, SIFT, SURF
3. za klasifikaciju: Support Vector Machine (SVM), klasična feedforward neuronska mreža (MLP), linearna regresija, k-najbližih suseda (k-NN) 
Predviđeno je isprobavanje obrade različitim pristupima, pa odabiranje onog čiji rezultati deluju najbolje.

- **Poređenje performansi:**
Za algoritme u kojima je potrebno podešavati određene parametre podela podataka na trening, validacioni i testni skup, sa približno istim odnosima predstavnika klasa koje se posmatraju, i unakrsna validacija.
Za druge algoritme podela podataka na trening i test skup, sa približno istim odnosima predstavnika klasa koje se posmatraju.

- **Podaci:**
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T
Skup podataka je unapred pripremljen i javno dostupan na navedenom linku.
Skup sadrži više od deset hiljada slika.
Većina podataka je precizno označena, dok kod nekih postoji neodredjenost, pa su pojedini atributi označeni sa unknown/undefined ili uopšte ne postoje. Takvi podaci će biti dodatno analizirani i biće procenjeno da li se nedostaci u opisu na neki način mogu ignorisati ili će takvi podaci biti izbačeni.

- **Validacija:**
Primarno izračunavanjem odziva klasifikacionog algoritma pošto je cilj što više smanjiti broj false negatives.
Dodatan vid provere može predstavljati validacija po F1 metrici.

- **Link na Github repozitorijum:**
https://github.com/SimicSvetislav/sc_project_lesions

**Comment by StefanAndjelic** [comment]
Tema odobrena, srecan rad!
