### ISSUE TITLE
Chest X-Ray Image Classification (Pneumonia)

### ISSUE THREAD

**Issue by aleksandarskrbic** [ftn-ai-lab/sc-2018-e2#2]
- **Članovi tima:**
    Aleksandar Škrbić RA153-2015, Grupa 8.
    Asistent : Miroslav Kondić
    @miroslavftn

- **Definicija problema:**
    Klasifikacija rendgenskih snimaka pluća (NORMAL or PNEUMONIA). Problem koji se rešava je binarna klasifikacija. Cilj projekta je da se problem reši putem klasičnih machine learning metoda i putem deep learning metoda i da se uporede krajnji rezultati.

- **Algoritmi koji će se koristiti:**
***Feature Extraction Algoritmi***: HOG, Local binary patterns, CNN, Autoencoder, LDA.
***Klasifikacioni Algoritmi***: SVM, Gradient Boosting, MLP.

- **Skup podataka:**
     Dataset je preuzet sa kaggle-a: https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia.
    Sastoji od trening, test i validacionih podataka. Za treniranje modela koristiće se trening i test set. Kako bi se dodatno utvrdila preciznost modela, koristiće se validacioni set, koji se sastoji od 16 snimaka.

- **Metodologija:**
Osnovna ideja je odraditi feature extraction sa slike i zatim dobijene rezultate propustiti kroz klasifikacioni algoritam.

- **Metode evaluacije:**
Accuracy, F1 score, precision and recall.

**Comment by miroslavftn** [comment]
Tema odobrena! Dodaj samo link ka git repozitorijumu.

**Comment by aleksandarskrbic** [comment]
Github repo link: https://github.com/aleksandarskrbic/sc_projekat
