### ISSUE TITLE
Predefinisani projekat za 60 bodova (ocjene 9 i 10)

### ISSUE THREAD

**Issue by jovan996** [ftn-ai-lab/sc-2018-e2#21]
Student
Jovan Grgur RA54/2015

Definicija problema:
Video zapis poseduje dve pokretne linije koje je potrebno detektovati Hough transformacijom. Cifre prolaze iza pokretnih linija. Cifre koje prođu ispod prve linije treba sabrati, a cifre koje prođu ispod druge linije treba oduzeti od konačnog rezultata.Pokušati rešiti slučaj preklapajućih cifara koje istovremeno prelaze preko linije, a nalaze se jedna preko druge u određenoj meri. Potrebno je postići tačnost prepoznavanja od bar 95%

Repozitorijum:
https://github.com/jovan996/SoftComputing2018

Asistent:
Stefan Andjelic @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Niste ispunili uslov za izlazak u roku za 11.02.2019. Vas repozitorijum ne sadrzi kod.
