### ISSUE TITLE
Provjera da li se odredjeni covjek nalazi na slici

### ISSUE THREAD

**Issue by milos996** [ftn-ai-lab/sc-2018-e2#27]
- Tim:
  Milos Ivankovic RA155-2015 , Grupa 2
- Repozitrojium
  https://github.com/milos996/Soft-project-2018-19
- Asistent: 
  Miroslav Kondic @miroslavftn 
- Definicija problema:
  Prepoznavanje da li se odredjeni covjek nalazi na odredjenoj slici 
- Skup podataka
  Rucno prikupljeni podaci zajedno sa vec postojecim skupom podataka. Vec postojeci skup podataka ce se koristit za obucavanje mreze da prepozna da li se na slici nalazi covjek ( odnosno lice covjeka,  dodatno cu dodati ovaj set podataka dok nadjem najbolje odgovarajuci skup podataka). Rucno prikupljeni podaci ce se koristiti radi utvrdjivanja postojanja zadatog covjeka koji se mora naci na zadatoj slici.
- Implementacija
  Koriscenjem  SVM i HOG istrenirati i validirati da li se na ucitanim slikama nalazi lice covjeka. Koristeci metod klizeceg prozora proci kroz zadatu sliku radi odredjivanja pozicija covjekovog lica. Koriscenjem metode klasterovanja nenadgledanog ucenja izdvojiti podatke za svako lice koje se pojavilo na zadatoj slici i uporediti sa zadatim licem za koje cemo provjeriti da li se nalazi na slici.
- Metod evaluacije
  Korisnik ce viditi da li se zadato lice nalazi na zadatoj slici ( korisnik ce znati koje lice se pretrazuje na kojoj slici).

**Comment by miroslavftn** [comment]
Tema odobrena, ali sam projekat je za nizu ocenu. Tezina je u rangu lakog predefinisanog zadatka. Ako zelis vecu ocenu, smisli kako mozes da ga zakomplikujes. SVM i HOG smo radili na vezbama, tako da nista novo ne obuhvata tvoj projekat.
