### ISSUE TITLE
Generisanje lažnih lica pomocu  Generative Adversarial Network (GAN)

### ISSUE THREAD

**Issue by NicicDamjan** [ftn-ai-lab/sc-2018-e2#3]
**Članovi tima:**
Damjan Ničič (RA133/**2014)**
Stefan Stamenković (RA100/**2015**)
Asistent: Miroslav Kondić
Repozitorijum: https: https://github.com/NicicDamjan/SoftKompjuting

**Problem koji se rešava:**
Planiramo da obucimo GAN model u cilju generisanja laznih slika cija distribucija verovatnoce priblizno odgovara distribuciji verovatnoce orginalnog skupa podataka.

**Algoritmi koji će se koristiti:**
 Generative Adversarial Network (GAN).

**Tehnologije koje se koriste**
Za dizajn i proces obuke modela ćemo koristiti čist Tensorflow.

**Metrika za poređenje performansi algoritama i/ili parametara algoritma**
 S obzirom na to da zelimo da generisemo lazne slike, evaluaciju resenja cemo vrsiti racunajuci Inception Score. Takodje cemo probati da izracunamo i Frechet Inception Distance-u koja se bolje pokazuje kao mera evaluacije GAN mreze"

**Podaci koji se koriste:**
 Skup podataka je javno dostupan na sledecem sajtu: http://vis-www.cs.umass.edu/lfw/ 

**Na koji način planirate validaciju rešenja?**
Validaciju rešenja ćemo vršiti poređenjem slika unutar našeg skupa podataka sa generisanim slikama, odnosno biće mera u kojoj je Generator uspeo da "prevari" Diskriminator

**Comment by miroslavftn** [comment]
Kako planirate da generisete nevidjene slike? Sta  ce biti ulaz? 
Kako planirate da koristite matricu konfuzije za merenje performansi? 
Kako radite validaciju resenja? Ovde je vise opisan proces ucenja, a ne sama validacija. Kako poredite generisane slike sa originalnim?

**Comment by NicicDamjan** [comment]
Planiramo da obucimo GAN model u cilju generisanja laznih slika cija distribucija verovatnoce priblizno odgovara distribuciji verovatnoce orginalnog skupa podataka.
Izvinjavamo se, prvobitno smo hteli nesto drugo da predlozimo kao temu za projekat pa smo se na kraju zbunili u procesu. S obzirom na to da zelimo da generisemo lazne slike, evaluaciju resenja cemo vrsiti racunajuci Inception Score. Takodje cemo probati da izracunamo i Frechet Inception Distance-u koja se bolje pokazuje kao mera evaluacije GAN mreze.

**Comment by miroslavftn** [comment]
Izmeni trenutni opis issue-a ili zatvorite ovaj i napravite novi sa finalnim opisom sta zelite da radite.
