### ISSUE TITLE
Predefinisani projekat za 7 i 8

### ISSUE THREAD

**Issue by lukovicns** [ftn-ai-lab/sc-2018-e2#4]
**Clan:** Milos Lukovic, RA100/2014

**Definicija problema**: Sumiranje brojeva koji prelaze liniju

**Repozitorijum**: https://github.com/lukovicns/SOFT-2018

**Asistent**: Miroslav Kondic

**Comment by miroslavftn** [comment]
Link ka repozitorijumu nije validan
