### ISSUE TITLE
Crtanje i upravljeanje racunarom pomocu gestikulacija ruke

### ISSUE THREAD

**Issue by FJakovljevic** [ftn-ai-lab/sc-2018-e2#47]
Članovi tima:
    Filip Jakovljevic RA13-2015, Grupa 7.
    Asistent : Miroslav Kondić
    @miroslavftn
Problem koji se rešava:
    Simulacija crtanja ili uopste upravljanje racunarom pomocu gestikulacija sake.
    U principu neki cilj bi mi bio da se levom sakom oznaci komanda a desnom upravlja, takodje ako bih uspeo implementiram crtanje svakako mislim da bih prebacio to i na neko upravljanje recimo nekom igricom, gde bi na osonovu prepoznate gestikulacije sake upravljalo igricom.

Implementacija:
    Ideja je da se na pocetku programa kalibrise boja sake korisnika tako sto ce korisnik namestiti saku da se na deo ekrana koji bude uokviren crvenim kvadratom. Posle kalibracije vrsice se tehnike za otklanjanje suma  Median Blurring (mislim prvenstveno ova jer bolje zadrzava jacinu ivica od Gaussian Blurring). Na osnovu boje koze korisnika i slike pravice se maske na koje ce se primenjivati erozija i dilacija za ponovno otklanjanje suma. 
    Za samu detekciju i klasifikaciju gestikulacije sake nisam jos odlucio tacno sta cu koristiti ali ovo su neke opcije o kojima razmatram:

   1. Convex hull algoritmom preko koga je moguce odrediti isto oblik u kome se saka nalazi ili neka kombinacija mozda sa Haar cascades (za detekciju gestikulacije leve sake). Recimo da bi ako bi bila leva saka otvorena i svih pet prstiju rasireni onda bi se ako je na desnoj ispruzen kaziprst crtalo njime i druge kombinacije.
   2. HOG sa SVM-om mada nisam siguran da li ce ovakvo detektovanje gestikulacije uspeti
   3. Neuronska mreza
   4. Neka kombinacija

Najveci problem svakako mislim da ce biti kada se saka nadje ispred lice i nadam se da cu uspeti da ga resim i verovatno ce rezultati zavisiti od osvetljenja.

Evaluacija:
    Validacija ce biti u realnom vremenu (reakciju na pokrete ruke).

Podaci koji se koriste:
   Ako ne uspem da nadjem slike gestikulacija sake koje mi odgovaraju na internetu sam cu ih napraviti.

link:
https://github.com/FJakovljevic/softProject

**Comment by miroslavftn** [comment]
Nedostaje link ka repozitorijumu.
