### ISSUE TITLE
Generisanje rezultata u toku partije snukera

### ISSUE THREAD

**Issue by aleksadjurdjulov** [ftn-ai-lab/sc-2018-e2#65]
Članovi: Aleksa Đurđulov RA157/2015, Grupa 5
Asistent: Ivan Perić @ivan7792

Problem koji se rešava:
Praćenje rezultata u toku partije snukera. Snuker je britanska igra koja je veoma slična bilijaru, sa određenim razlikama. Za razliku od bilijara, kugle se ne dodeljuju takmičaru (ili timu) već oba igrača igraju sa istim kuglama, naizmenično. Na osnovu pravila poznato je kada se dodeljuju poeni i kada se potez predaje protivniku. U svakoj partiji postoji unapred određen broj kugli (sa svojima bojama) i njihov raspored na stolu.

Algoritam:
Prepoznavanje pozicije svake od kugli korišćenjem OpenCV biblioteke na osnovu njene boje (s obzirom da je unapred poznat broj i boja svake od kugli može se koristiti opseg boje), kombinovano sa Hough transformacijom (veličina svake kugle je ista i menja se minimalno - u zavisnosti od udaljenosti od kamere) radi veće preciznosti. Takođe, činjenica je da se sve kugle moraju nalaziti na stolu, te se lako mogu eliminisati sve "kugle" pronađene van stola. Poznato je da postoji određeni vremenski period tokom kojeg se igrač priprema za udarac (uglavnom između 15 i 20 sekundi, radi sigurnosti može se pretpostaviti znatno manja vrednost) tokom kojeg se kugle ne pomeraju (postavio bi se minimum za "pomeraj" kao garancija da se stvarno dešava pomeraj), te je lako prepoznati pauzu između udaraca. Ova informacija olakšava rasuđivanje o ostvarenim poenima (ili načinjenim faulovima) jer se bodovanje vrši poređenjem prethodnog i tekućeg stanja, u vidu broja određenih kugli na stolu. Bitno je znati i sa kuglom koje boje je bela kugla prvo napravila kontakt - to bi se vršilo praćenjem njene putanje, tj. kada bela kugla naglo promeni putanju (pazeći da se ne radi o "zidu" stola) pretpostavka je da je došlo do kontakta. Bodovanje se vrši na osnovu unapred poznatog pravilnika upoređivanjem uzastopnih stanja kugli na stolu.

Podaci:
Lično prikupljen skup video snimaka sa interneta.

Validacija:
Može se vršiti empirijski, ili ukoliko snimak prikazuje i rezultat (što je skoro uvek slučaj) - automatski upoređivanjem očitanog rezultata iz frejma.

Link ka repozitorijumu:
https://github.com/djuka996/soft-projekat

**Comment by ivan7792** [comment]
Tema je ok. 

Par izazova sa kojima ćete se sresti, na koje trebate računati:
- Pošto snimke tražite ručno, verovatno ćete imati problema sa različitim nivoom osvetljenja stola, pa ćete sam opseg boja koji navodite morati napraviti fleksibilnijim. Da li ćete ostati na opsezima boja, ili ćete klasterovati piksele stola na tačno određen broj boja, zavisi od Vas.
- Detekcija kolizije objekata. Kada na stolu imate dve kugle, imaćete detekciju kolizije objekata u slučaju kada one dođu u kontakt. Može se rešiti i na druge načine, a ovo je jedan od njih. Bela kugla ne mora naglo promeniti putanju, ukoliko je kontakt slab i/ili nije čeoni.
- Poene možete detektovati kada na stolu nema promene i aktivnih pokreta, a stanje je različito od prethodnog mirnog stanja. Bolje je nego hadkodiranje vremenskih intervala.

Tema odobrena, srećan rad.

**Comment by aleksadjurdjulov** [comment]
Pozdrav Ivane,

Što se tiče poena, to je i bila ideja, samo je nisam obrazložio korektno -
kretanje počinje pomeranjem bele kugle.
Zanima me koliko snimaka je neophodno da prikupim? U jednom meču može se
odigrati najmanje 4, a najviše 35 frejmova (na početku svakog frejma kugle
se ređaju ispočetka ).
Što se tiče boje, da li se može realizovati nekim principom Color Picker-a,
jer se zna koja se kugla nalazi na kojoj poziciji na početku frejma, pa da
se nakon toga odredi njen opseg.

**Comment by ivan7792** [comment]
Pošto će se Vaš projekat bazirati na obradi slike, a ne na obučavanju nekih nadgledanih modela, broj snimaka nije od krucijalne važnosti. Iskoristite snimke na kojima model radi dobro, i one na kojima to nije slučaj da pokažete koji ste slučajeve pokrili a koje bi trebalo doraditi.

Bilo bi dobro da to radite dinamički, da ne mora korisnik svaki put označavati boje pre početka partije ColorPicker-om. Sam sto možete segmentirati na takav način, a onda ostale elemente unutar stola (ne ostale van stola, gde možete imati dosta šuma), možete na sličan ili na neki drugi način (kao primer sam Vam naveo klasterovanje).
