### ISSUE TITLE
Analiza ortopantomografskih(opt) snimaka vilice

### ISSUE THREAD

**Issue by Vekisa** [ftn-ai-lab/sc-2018-e2#66]
Student:
Veljko Mošorinski RA75/2015

Problem:
Na osnovu snimka vilice potrebno je detektovati postojanje svakog zuba pojedinačno. Za početak, svaki detetovan zub će biti izdvojen, potom klasifikovan, a nakon toga će biti određeno postojanje plombe ili određenog procesa u okviru zuba i u njegovoj okolini, što se na slici manifestuje u obliku mestimičnih zatamnjenja/prosvetljenja određenog oblika. Na kraju, svaki zub će biti svrstan u kvadrant kome pripada.

Algoritmi:
HOG,CNN,SVM

Metrika:
Performanse u ovom problemu nisu ključan faktor, ali svakako da analiza treba biti završena u "podnošljivom" vremenu.

Podaci:
Ručno prikupljen skup podataka. Potrebno ih je rućno obraditi izdvajanjem zuba u pojedinačne slike.

Validacija:
Biće izvršena analiza rezultata nad određenim brojem primera od strane stručnog lica.

Git:
https://github.com/Vekisa/SoftProject.git

Asistent:
@ivan7792

**Comment by ivan7792** [comment]
Nisam siguran koliko ste istraživali na ovu temu, ali se nadam da ste potrošili dovoljno na vremena na to (dali smo studentima nekoliko nedelja) i da znate koliko ste složen projekat uzeli.

Zapažanja na osnovu prijave:
- Ručno prikupljanje podataka će biti gotovo nemoguće obaviti. Svi snimci koji nađete će biti u različitim formatima (neće biti standardni) što će otežati labeliranje. Neće svaki uređaj davati iste snimke.
- Samo labeliranje će biti problem. Morate i sami biti upućeni u čitanje OPT snimaka. A sa druge strane, ako radite nadgledano izdvajanje zuba (image segmentation na nivou piksela), moraćete sami iznačiti svaki zub, što će oduzeti ogromnu količinu vremena.
- Detektovanje plombi je ponekad težak zadatak i za čoveka jer nisu toliko uočljive na ovim snimcima u slučajevima kada su male, a kamoli za mašinu koja će u ovom slučaju raspolagati jako malom količinom podataka.
- Na koji način planirate rešavati detekciju zuba, njihove različite dimenzije i slično? CNN?


Projekat je lep, ali mi se iz prijave čini da niste posvetili dovoljno vremena za istraživanje pre same prijave, pa još uvek ne vidite gomilu problema sa kojima ćete se susresti. Ovakav tip projekta može biti master rad, ili čak i više (u zavisnosti na koji način pristupite rešavanju). Ukoliko ste sigurni da želite ovo, mi vas nećemo sprečavati, ali imate i naš savet i pregled situacije. Ukoliko odustanete, dodeljuje Vam se predefinisani projekat.

**Comment by Vekisa** [comment]
Poštovani Ivane,

Želeo bih ipak da se još malo psavetujem sa Vama pre nego što odlučim.
Vaša zapažanja potpuno uvažavam i svestan sam bio njih od kad razmišljam o
projektu.

Odgovori na njih su sledeći:
     1. Podatke ću dobiti narednih dana iz arhive Klinike za
stomatologiju(između 50 i 100 snimaka). Pisao sam molbu zajedno sa
studentom tog fakulteta, zarad studentskog istraživanja i odobrili su je.
Obzirom da su snimci sa istog mesta, snimani na njihovom radiološkom
odeljenju, verujem da će formati biti odgovarajući.
     2. Čitanje OPT snimaka mi nije strano, trudio sam se da se što više
uputim u to, a i napomenuo bih da ću imati potpunu pomoć od pomenutog
studenta, koji je na završnoj godini Medicinskog fakulteta(stomatologije).
         Problem koji me je brinuo je upravo taj koji ste pomenuli,
izdvajanje svakog zuba pojedinačno. Ako i zanemarim vreme koje je potrebno,
da kazem da ću imati odgovarajuću pomoć da ubrzam taj proces dovoljno brzo,
i dalje me brine. Svestan sam da             će svaka ta novoformirana
fotografija(svakog pojedinačnog zuba) morati da bude određenog
formata/veličine, što je problem. Ukoliko bi mogli taj deo da
prokomentarišete/da me posavetujete, bio bih Vam zahvalan. Da li će npr. to
moći da se odradi               nekim programom za obradu slike, pa se sve
te nove slike formirati skaliranjem na određenu veličinu? Ili nešto slično
tome...
     3. Imao sam priliku da pričam o tome sa jednim od predavača na
Medicinskom fakultetu. Detektovanje plombi uglavnom nije problem. Bile one
male i velike, na slikama se javljaju u obliku jakog prosvetjenja, da kažem
"potpune" beline, što se inače na               pojavljuje na ovim snimcima
ukoliko ih nema i ukoliko je snimak adekvatno napravljen. Njihovu detekciju
čak i ne zamisljam da odradim koristeći CNN, niti mislim da mi treba
kolekcija podataka za to. Dao bih sebi pravo da sam definišem pojavu plobe
           na slici, kao neku pojavu "najjače" beline, određenog minimalnog
i maksimalnog radiusa, u okviru samog zuba.
     4. Detekciju planiram baš tako, koristio bih CNN.

Slažem se velikom većinom sa onim što ste napisali i svestan sam problema.
Ne želim da radim po svaku cenu ukoliko Vi mislite da nije moguće ovo
završiti do datog roka, ali ne želim ni lako da odustanem. Ideja je iznikla
van okvira ovog projekta, i u planu mi je da pokušam da uradim nešto dobro,
zahtevnije. Nisam siguran koliko bi bilo potrebno uraditi za predmet i da
li je to moguće u ovom vremenskom periodu. Ukoliko ste u mogućnosti,
prokomentarišite još jednom sada sa malo pojašnjenom verzijom projekta.
Hvala unapred!

Srdačan pozdrav,
Veljko Mošorinski RA75/2015


чет, 3. јан 2019. у 13:29 Ivan Perić <notifications@github.com> је
написао/ла:

**Comment by ivan7792** [comment]
1. Odlično, ovo i jeste poenta projekata po ličnom izboru - da rešavate nešto što je Vama interesantno i da istražujete. Iako 100-150 sličica svakako neće biti neka zavidna količina, ok je za početak nečega što kasnije možete proširivati.
2. Ako ovo posmatrate kao problem segmentacije nad celim OPT snimkom, nemate ovakav problem.  Zato sam pitao na koji način ovo planirate rešavati. Ukoliko na celoj slici samo zamaskirate zube, ne morate se toliko brinuti o skaliranju (bar ne u ovom problemu detekcije plombi). Labeliranje bi se svodilo na to da napravite odgovarajuću masku za svaki snimak (u radu koji sam Vam prikačio - maska je na početku strane 17 (annotated)).
3. Kada detektujete i izolujete pojedinačne zube, detektovanje plombe nije veliki problem, slažem se. To je samo sitno proširenje, ukoliko je prethodni korak detekcija zuba. U slučaju kada radite sa celim snimkom, bez prethodne detekcije zuba, to bi bio teži zadatak zbog šuma koji će se pojavljivati svugde, a koji nije lako izolovati. 


Rad u kome možete naći dosta različitih state-of-the-art pristupa: https://arxiv.org/pdf/1802.03086.pdf
Dosta toga smo mi već i radili na vežbama. Ne morate se ograničavati na rad, ali Vam možda da neke ideje za preprocessing.



Što se tiče Vašeg opsega projekta, dovoljno je odraditi segmentaciju zuba i detekciju prombi. Tu uključujete i CNN koje nismo implementirali na vežbama. Da bi postigli što bolje performanse modela, verovatno ćete imati i neke metode obrade izvornih OPT snimaka pre nego što ih pošaljete na CNN (što ćete videti i u radu) čime ćete pokriti gradivo celog predmeta (detekcija ivica, boje, ...). Ako zanemarimo proces labeliranja (kreiranja maski), sjajan projekat. 
Isključivo od Vas zavisi koliko vremena možete uložiti u labeliranje, da bi Vam što više vremena ostalo za kodiranje. Može se uraditi u ovom vremenskom intervalu (imate skoro mesec dana). Pošto snimke još uvek niste dobili sa klinike (nadamo se da neće kasniti), možete osmisliti ceo pipeline i ponešto implementirati, a onda krenuti sa labeliranjem kada snimci stignu. Izlabelirate 20 snimaka, pa probate, pa 50 i probate, pa sve. Model bi trebao raditi sve bolje kako dodajete snimke (ako ste dobro napravili model) i ako su podaci ok. Na Vama je.
Ukoliko se ipak desi da odustanete, projekat možete prebaciti na predmet "Neuronske mreže" na masteru (ukoliko to budete slušali) - gde se detaljnije rade i CNN, a koji kreće od jeseni 2019. Interesantan je projekat, pa bi bilo dobro da ga uradite na nekom od naših predmeta.
