### ISSUE TITLE
Detekcija i klasifikacija karata za igru

### ISSUE THREAD

**Issue by BorisJov** [ftn-ai-lab/sc-2018-e2#72]
**Autor:** Boris Jovanović, RA12/2015
**Asistent:** @miroslavftn 

**Motivacija:**
Inspiracija za projekat jeste isustvo sa turnira bridža gde je potrebno uneti raspodele karata nakon završene partije radi evidencije. Ovaj proces obično traje nekoliko minuta i nije zanimljiv, te bi bilo potrebno ubrzati.
Karte se mogu jednostavno slikati, direktno prepoznati i uvesti u evidenciju.

**Metodologija:**
Projekat se sastoji iz dva modula:
I) Detekcija karata
- Oslanjajući se na OpenCV potrebno je prepoznati pravougaonik karte, skinuti boje/primeniti filtere i izdvojiti svaku kartu sa slike

II) Klasifikacija karata
- Koristeći konvolucionu neuronsku mrežu potrebno je klasifikovati karte prema boji i znaku (ukupno 52)

**Metrika/Validacija:**
Ulazi će se podeliti u train/test deo (9:1). Finalni rezultat će biti izražen u postotku pogođenih karata.

**Podaci:**
Za sada nađen sledeći skup:
https://www.kaggle.com/luantm/playing-card

**Repozitorijum:**
https://github.com/BorisJov/CardRecognition

**Comment by miroslavftn** [comment]
ako budu pokrivene karte iz razlicitog ugla i perspektive, projekat je za najvisu ocenu.

**Comment by BorisJov** [comment]
Tako je, karte mogu biti i rotirane, projekat je planiran za najvisu ocenu.

**Comment by BorisJov** [comment]
Promenjen skup podataka:
https://drive.google.com/open?id=19-Vmc1EKpuNK3uUTqjb9hfCBUWbGraov
