### ISSUE TITLE
Detekcija dijabetičkog makularnog edema (degeneracije oka) na osnovu OCT snimaka

### ISSUE THREAD

**Issue by AndrijanaJeremic** [ftn-ai-lab/sc-2018-e2#83]
**Članovi tima:** Milica Makarić RA80/2015 i Andrijana Jeremić RA125/2015
**Asistent:** Ivan Perić @ivan7792 

**Motivacija:** Rešenje ovog problema pomoglo bi stručnjacima iz oftamoloških oblasti da od velike količine snimaka svoj fokus preusmere samo na one problematične – sa dijagnozom. Na osnovu izlaza našeg programa dobiće informacije da li se radi o bolesnom ili zdravom oku. Na ovaj način će smanjiti svoje vreme utrošeno na proučavanje velikog broja snimaka među kojima se nalaze kako snimci oka sa degeneracijom makule tako i oni bez.

**Skup podataka:** Skup podataka koje ćemo koristiti nalazi se na linku https://www.kaggle.com/paultimothymooney/kermany2018 u folderima OCT2017/test/DME i OCT2017/test/NORMAL.

**Link ka repozitorijumu:** https://github.com/AndrijanaJeremic/DME_detection.git

**Metodologija:** Metodologija obuhvata augmentaciju podataka (rotacija, promena intenziteta osvetljenja..), korišćenje HOG deskriptora i klasifikatora poput SVM, NM. Planirano je da se naprave histogrami po x i y osama i da se oni šalju na klasifikator. Takođe, biće isprobano i slanje slika piksel po piksel. U planu je i samostalno istraživanje o drugačijim i novijm načinima analiziranja ovakvog tipa snimaka, a zatim upoređivanje rezultata svih različitih pristupa koji su primenjeni.

**Evaluacija:** Snimci će biti podeljeni na test i train skup i koristićemo neku od mera za procenu performansi algoritma koju smo obrađivali na predmetu Soft kompjuting.

**Comment by ivan7792** [comment]
HOG (još bolje je da probate i još neke druge deskriptore koji postoji u openCV) u kombinaciji sa klasifikatorom (SVM, VNM, ...) je osnovna kombinacija koju smo radili na vežbama i možete iskoristiti taj kod skoro direkno.

Za više ocene je neophodno da uradite nešto od alternativnih pristupa koji ste naveli (histogrami, piksel-wise,... ) i da proverite šta su drugi ljudi radili na sličnu temu i probate neke od tih pristupa, da bi potpuno zaokružili ceo projekat.

Tema odobrena, srećan rad.
