### ISSUE TITLE
Detekcija (prepoznavanje) akorda na gitari na osnovu oblika šake i položaja prstiju

### ISSUE THREAD

**Issue by recimo** [ftn-ai-lab/sc-2018-e2#97]
**Članovi:** 
Nikola Ilić RA189/2015, Grupa 9

Asistent:
Ivan Perić
@ivan7792 

**Problem:**
Prepoznavanje akorda na gitari na osnovu oblika šake, položaja prstiju i položaja šake na vratu gitare.
Zbog kompleksnosti samog problema, analiziraće se samo određeni deo vrata gitare i određeni broj različitih akorda.

**Metodologija:**
Rešenje će podrazumevati detekciju ruke, vrata gitare, žica, polozaj vrhova prstiju na žicama gitare i na pragovima na vratu, i na osnovu toga prepoznavati koji akord je u pitanju. Takođe korišćenjem HOG deskriptora i klasifikatora kao što je SVM će se klasifikovati slike iz trening seta, skalirati slike, rotirati i postavljati odgovarajući ugao i taj pristup porediti sa prvim ukoliko to bude bilo potrebno.
Trening set će sadržati 30-40 slika koje će biti posebno napravljene (fotografisanje svakog akorda posebno). Zbog same kopleksnosti teme i malog skupa podataka za treniranje pretpostavka je da rešenje neće davati dobre rezultate.

**Link ka repozitorijumu:**
https://github.com/recimo/ChordDetection

**Comment by ivan7792** [comment]
- Na koji način i na kom mestu u celom Vašem pipeline-u planirate korišćenje HOG deskriptora i klasifikatora? Ukoliko problem svedete na klasifikaciju sličica akorda, to se manje-više svodi na primer klasifikacije koji smo radili na vežbama i za maksimalnu ocenu 6.

Za više ocene bi trebali da obradite neke druge pristupe koji bi uključivali obradu slike (detekcija ruke, detekcija vrata gitare, aproksimacija žica i položaja prstiju na njima i slično) i na osnovu toga da donosite odluke koji je akord u pitanju. Taj pristup možete uporediti sa HOG+klasifikator pristupom i to staviti na poster.

**Comment by recimo** [comment]
To je i planirano. Krenuo sam taj deo da opisujem u problemu, pa sam hteo detaljnije u metodologiji da ga opišem, ali iz nekog razloga sam to ispustio... Hvala što ste mi ukazali na to. Ispravljena je greška.
